name: BuildAndRelease
on: push

jobs:
  main:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Build
        run: platformio run -e esp32doit-devkit-v1
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .pio/build/esp32doit-devkit-v1/firmware.bin
          token: ${{ secrets.GITHUB_TOKEN }}
